spring:
    datasource:
        url: jdbc:mysql://localhost:3306/quanlycuahang
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: none
            #ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect #every database have varies dialect. Configuration connection databe. Ex: mysql
                enable_lazy_load_no_trans: true