server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/doan
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: none
            #ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect #every database have varies dialect. Configuration connection databe. Ex: mysql
                enable_lazy_load_no_trans: true
                event:
                    merge:
                        entity_copy_observer: allow #fix bug : Multiple represent in same entity
key: AIzaSyD_qbY0HwQaGA9tbMkOIP_4Mq4wvjZ_B14
